export const why_not_me = [
  {
    id: 0,
    text: "...",
    range: [0, 10.5],
  },
  {
    id: 1,
    text: "Escaping nights without you with shadows on the wall",
    range: [10.6, 15.05],
  },
  {
    id: 2,
    text: "My mind is running wild tryin' hard not to fall",
    range: [15.06, 20.5],
  },
  {
    id: 3,
    text: "You told me that you love me but say I'm just a friend",
    range: [20.6, 25.2],
  },
  { id: 4, text: "My heart is broken up into pieces", range: [25.3, 28.2] },
  { id: 5, text: "'Cause I know I'll never free my soul", range: [28.3, 32.5] },
  {
    id: 6,
    text: "It's trapped between true love and being alone",
    range: [32.6, 37.7],
  },
  {
    id: 7,
    text: "When my eyes are closed the greatest story told",
    range: [37.7, 42.5],
  },
  {
    id: 8,
    text: "I woke and my dreams are shattered here on the floor",
    range: [42.5, 48.2],
  },
  { id: 9, text: "Why oh why tell me why not me", range: [48.2, 53.4] },
  { id: 10, text: "Why oh why we were meant to be", range: [53.4, 57.7] },
  { id: 11, text: "Baby I know I could be all you need", range: [57.7, 63] },
  { id: 12, text: "Why oh why oh why", range: [63, 67] },
  { id: 13, text: "I wanna love you", range: [67, 70] },
  { id: 14, text: "If you only knew how much I love you", range: [70, 75] },
  { id: 15, text: "So why not me", range: [75, 79] },
  {
    id: 16,
    text: "The day after tomorrow I'll still be around",
    range: [79, 83.5],
  },
  {
    id: 17,
    text: "To catch you when you fall and ever let you down",
    range: [83.5, 88.4],
  },
  {
    id: 18,
    text: "You say that we're forever our love will never end",
    range: [88.4, 93.3],
  },
  {
    id: 19,
    text: "I've tried to come up but it's drowning me to know",
    range: [93.3, 98],
  },
  { id: 20, text: "You'll never feel my soul", range: [98, 100.4] },
  {
    id: 21,
    text: "It's trapped between true love and being alone",
    range: [100.4, 105.4],
  },
  {
    id: 22,
    text: "When my eyes are closed the greatest story told",
    range: [105.4, 110],
  },
  {
    id: 23,
    text: "I woke and my dreams are shattered here on the floor",
    range: [110, 115],
  },
  { id: 24, text: "Tell me baby", range: [115, 116.4] },
  { id: 25, text: "Why oh why tell me why not me", range: [116.4, 121] },
  { id: 26, text: "Why oh why we were meant to be", range: [121, 125.4] },
  { id: 27, text: "Baby I know I could be all you need", range: [125.4, 131] },
  { id: 28, text: "Why oh why oh why", range: [131, 134.7] },
  { id: 29, text: "I wanna love you", range: [134.7, 138] },
  { id: 30, text: "If you only knew how much I love you", range: [138, 142.8] },
  { id: 31, text: "So why not me", range: [142.8, 145] },
  { id: 32, text: "You won't ever know", range: [145, 150.5] },
  { id: 33, text: "How far we can go", range: [150.5, 155.2] },
  { id: 34, text: "You won't ever know", range: [155.2, 160] },
  { id: 35, text: "How far we can go (go)", range: [160, 164.8] },
  { id: 36, text: "Why oh why tell me why not me", range: [164.8, 169.7] },
  { id: 37, text: "Why oh why we were meant to be", range: [169.7, 174] },
  { id: 38, text: "Baby I know I could be all you need", range: [174, 179.2] },
  { id: 39, text: "Why oh why oh why", range: [179.2, 184.4] },
  { id: 40, text: "Why oh why tell me why not me", range: [184.4, 189.2] },
  { id: 41, text: "Why oh why we were meant to be", range: [189.2, 193.6] },
  {
    id: 42,
    text: "Baby I know I could be all you need",
    range: [193.6, 198.6],
  },
  { id: 43, text: "Why oh why oh why", range: [198.6, 202.8] },
  { id: 44, text: "I wanna love you", range: [202.8, 205.8] },
  {
    id: 45,
    text: "If you only knew how much I love you",
    range: [205.8, 210.7],
  },
  { id: 46, text: "So why not me", range: [210.7, 213] },
  { id: 47, text: "...", range: [213, 220] },
];

export const that_girl = [
  {
    id: 1,
    text: "There's a girl but I let her get away",
    range: [0, 3],
  },
  {
    id: 2,
    text: "It's all my fault cause pride got in the way",
    range: [4, 7],
  },
  {
    id: 3,
    text: "And I'd be lying if I said I was ok",
    range: [8, 11],
  },
  {
    id: 4,
    text: "About that girl the one I let get away",
    range: [12, 16],
  },
  {
    id: 5,
    text: "I keep saying no",
    range: [17, 20],
  },
  {
    id: 6,
    text: "This can't be the way we're supposed to be",
    range: [21, 25],
  },
  {
    id: 7,
    text: "I keep saying no",
    range: [26, 30],
  },
  {
    id: 8,
    text: "There's gotta be a way to get you close to me",
    range: [0, 5],
  },
  {
    id: 9,
    text: "Now I know you gotta",
    range: [0, 5],
  },
  {
    id: 10,
    text: "Speak up if you want somebody",
    range: [0, 5],
  },
  {
    id: 11,
    text: "Can't let him get away, oh no",
    range: [0, 5],
  },
  {
    id: 12,
    text: "You don't wanna end up sorry",
    range: [0, 5],
  },
  {
    id: 13,
    text: "The way that I'm feeling everyday",
    range: [0, 5],
  },
  {
    id: 14,
    text: "(Don't you know) no no no no",
    range: [0, 5],
  },
  {
    id: 15,
    text: "There's no home for the broken heart",
    range: [0, 5],
  },
  {
    id: 16,
    text: "no no no no",
    range: [0, 5],
  },
  {
    id: 17,
    text: "There's no home for the broken",
    range: [0, 5],
  },
  {
    id: 18,
    text: "There's a girl but I let her get away",
    range: [0, 5],
  },
  {
    id: 19,
    text: "Its my fault cause I said I needed space",
    range: [0, 5],
  },
  {
    id: 20,
    text: "I've been torturing myself night and day",
    range: [0, 5],
  },
  {
    id: 21,
    text: "About that girl, the one I let get away",
    range: [0, 5],
  },
  {
    id: 22,
    text: "I keep saying no",
    range: [0, 5],
  },
  {
    id: 23,
    text: "This can't be the way we're supposed to be",
    range: [0, 5],
  },
  {
    id: 24,
    text: "I keep saying no",
    range: [0, 5],
  },
  {
    id: 25,
    text: "There's gotta be a way to get",
    range: [0, 5],
  },
  {
    id: 26,
    text: "There's gotta be a way to get you close to me",
    range: [0, 5],
  },
  {
    id: 27,
    text: "You gotta",
    range: [0, 5],
  },
  {
    id: 28,
    text: "Speak up if you want somebody",
    range: [0, 5],
  },
  {
    id: 29,
    text: "Can't let him get away, oh no",
    range: [0, 5],
  },
  {
    id: 30,
    text: "You don't wanna end up sorry",
    range: [0, 5],
  },
  {
    id: 31,
    text: "The way that I'm feeling everyday",
    range: [0, 5],
  },
  {
    id: 32,
    text: "(Don't you know) no no no no",
    range: [0, 5],
  },
  {
    id: 33,
    text: "There's no home for the broken heart",
    range: [0, 5],
  },
  {
    id: 34,
    text: "(Don't you know) no no no no",
    range: [0, 5],
  },
  {
    id: 35,
    text: "There's no home for the broken",
    range: [0, 5],
  },
  {
    id: 36,
    text: "No home for me no",
    range: [0, 5],
  },
  {
    id: 37,
    text: "No home cause I'm broken",
    range: [0, 5],
  },
  {
    id: 38,
    text: "No room to breathe (no)",
    range: [0, 5],
  },
  {
    id: 39,
    text: "And I got no one to blame",
    range: [0, 5],
  },
  {
    id: 40,
    text: "No home for me (no)",
    range: [0, 5],
  },
  {
    id: 41,
    text: "No home cause I'm broken",
    range: [0, 5],
  },
  {
    id: 42,
    text: "About that girl",
    range: [0, 5],
  },
  {
    id: 43,
    text: "The one I let get away",
    range: [0, 5],
  },
  {
    id: 44,
    text: "So you better",
    range: [0, 5],
  },
  {
    id: 45,
    text: "Speak up if you want somebody",
    range: [0, 5],
  },
  {
    id: 47,
    text: "Can't let him get away, oh no no",
    range: [0, 5],
  },
  {
    id: 48,
    text: "You don't wanna end up sorry (oh no)",
    range: [0, 5],
  },
  {
    id: 49,
    text: "The way that I'm feeling everyday",
    range: [0, 5],
  },
  {
    id: 50,
    text: "(Don't you know) no no no no",
    range: [0, 5],
  },
  {
    id: 51,
    text: "There's no home for the broken heart",
    range: [0, 5],
  },
  {
    id: 52,
    text: "(Don't you know) no no no no",
    range: [0, 5],
  },
  {
    id: 53,
    text: "There's no home for the broken (ooh)",
    range: [0, 5],
  },
  {
    id: 54,
    text: "You don't wanna lose that love",
    range: [0, 5],
  },
  {
    id: 55,
    text: "It's only gonna hurt too much",
    range: [0, 5],
  },
  {
    id: 56,
    text: "(I'm telling you)",
    range: [0, 5],
  },
  {
    id: 57,
    text: "You don't wanna lose that love",
    range: [0, 5],
  },
  {
    id: 58,
    text: "It's only gonna hurt too much",
    range: [0, 5],
  },
  {
    id: 59,
    text: "(I'm telling you)",
    range: [0, 5],
  },
  {
    id: 60,
    text: "You don't wanna lose at love",
    range: [0, 5],
  },
  {
    id: 61,
    text: "'Cause there's no home for the broken",
    range: [0, 5],
  },
  {
    id: 62,
    text: "About that girl",
    range: [0, 5],
  },
  {
    id: 63,
    text: "The one I let get away",
    range: [0, 5],
  },
];

export const monsters = [
  { id: 1, text: "I see your monsters", range: [0, 3] },
  { id: 2, text: "I see your pain", range: [0, 3] },
  { id: 3, text: "Tell me your problems", range: [0, 3] },
  { id: 4, text: "I'll chase them away", range: [0, 3] },
  { id: 5, text: "I'll be your lighthouse", range: [0, 3] },
  { id: 6, text: "I'll make it okay", range: [0, 3] },
  { id: 7, text: "When I see your monsters", range: [0, 3] },
  { id: 8, text: "I'll stand there so brave", range: [0, 3] },
  { id: 9, text: "And chase them all away", range: [0, 3] },
  { id: 10, text: "A cup of coffee still steaming", range: [0, 3] },
  {
    id: 11,
    text: "Staring back at me, it's blacker than the night",
    range: [0, 3],
  },
  { id: 12, text: "Ay, I'm awake but still sleeping", range: [0, 3] },
  {
    id: 13,
    text: "I keep telling myself I'll be alright (I won't)",
    range: [0, 3],
  },
  { id: 14, text: "And I know it can't get worse than today", range: [0, 3] },
  {
    id: 15,
    text: "Sitting here and she's trying to rehearse what to say",
    range: [0, 3],
  },
  {
    id: 16,
    text: "See, she's in the bathroom hoping I'm not in earshot",
    range: [0, 3],
  },
  { id: 1, text: "While she's getting used", range: [0, 3] },
  {
    id: 1,
    text: "To the sound of a teardrop, splash it hits the tile",
    range: [0, 3],
  },
  {
    id: 1,
    text: "And I know it's been a while since you seen me",
    range: [0, 3],
  },
  { id: 1, text: "Smile and laugh like I used to", range: [0, 3] },
  { id: 1, text: "I've been in denial since it happened", range: [0, 3] },
  { id: 1, text: "Just take me to the past", range: [0, 3] },
  {
    id: 1,
    text: "'Cause I just can't imagine losing you (too)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I can't explain this so I'll keep it all inside",
    range: [0, 3],
  },
  { id: 1, text: "Wear my pain, but it's masked by my pride", range: [0, 3] },
  { id: 1, text: "She came to hold me and she cried", range: [0, 3] },
  {
    id: 1,
    text: "Told me this as she stared into my eyes, said",
    range: [0, 3],
  },
  { id: 1, text: "I see your monsters", range: [0, 3] },
  { id: 1, text: "I see your pain", range: [0, 3] },
  { id: 1, text: "Tell me your problems", range: [0, 3] },
  { id: 1, text: "I'll chase them away", range: [0, 3] },
  { id: 1, text: "I'll be your lighthouse", range: [0, 3] },
  { id: 1, text: "I'll make it okay", range: [0, 3] },
  { id: 1, text: "When I see your monsters", range: [0, 3] },
  { id: 1, text: "I'll stand there so brave", range: [0, 3] },
  { id: 1, text: "And chase them all away", range: [0, 3] },
  { id: 1, text: "I can't, you won't like what you see", range: [0, 3] },
  {
    id: 1,
    text: "If you were in my head and had to hear my pleas",
    range: [0, 3],
  },
  {
    id: 1,
    text: "It's like I can't believe this is happening to me",
    range: [0, 3],
  },
  { id: 1, text: "And could someone please", range: [0, 3] },
  { id: 1, text: "Shut this fucking answering machine", range: [0, 3] },
  { id: 1, text: "So I can start leaving these messages", range: [0, 3] },
  { id: 1, text: "That you will never get", range: [0, 3] },
  { id: 1, text: "And all these cries for help", range: [0, 3] },
  { id: 1, text: "You'll never see and never check", range: [0, 3] },
  { id: 1, text: "But I guess it's easy for you to leave me", range: [0, 3] },
  { id: 1, text: "But believe me", range: [0, 3] },
  {
    id: 1,
    text: "See this isn't something that Ima just forget",
    range: [0, 3],
  },
  { id: 1, text: "I would trade it all for one more minute", range: [0, 3] },
  { id: 1, text: "Don't you see I really need you to talk to", range: [0, 3] },
  { id: 1, text: "I'm still sitting here wondering who did it", range: [0, 3] },
  { id: 1, text: "While I'm staring out our front door", range: [0, 3] },
  { id: 1, text: "Knowing you'll never walk through", range: [0, 3] },
  { id: 1, text: "Said you'd come right back", range: [0, 3] },
  { id: 1, text: "And now you're gone like that", range: [0, 3] },
  { id: 1, text: "A blank stare as I stand so alone", range: [0, 3] },
  { id: 1, text: "And know you're never coming home (damn)", range: [0, 3] },
  { id: 1, text: "I see your monsters", range: [0, 3] },
  { id: 1, text: "I see your pain", range: [0, 3] },
  { id: 1, text: "Tell me your problems", range: [0, 3] },
  { id: 1, text: "I'll chase them away", range: [0, 3] },
  { id: 1, text: "I'll be your lighthouse", range: [0, 3] },
  { id: 1, text: "I'll make it okay (yeah)", range: [0, 3] },
  { id: 1, text: "When I see your monsters", range: [0, 3] },
  { id: 1, text: "I'll stand there so brave", range: [0, 3] },
  { id: 1, text: "And chase them all away", range: [0, 3] },
  { id: 1, text: "I got a heart made of fool's gold", range: [0, 3] },
  { id: 1, text: "Got me feeling so cold", range: [0, 3] },
  { id: 1, text: "You keep chipping away", range: [0, 3] },
  { id: 1, text: "All the promises that I told", range: [0, 3] },
  { id: 1, text: "Felt like I was on those", range: [0, 3] },
  { id: 1, text: "They keep slipping away", range: [0, 3] },
  { id: 1, text: "I want nobody else", range: [0, 3] },
  { id: 1, text: "But it's hard to get to know me", range: [0, 3] },
  { id: 1, text: "When I don't know myself", range: [0, 3] },
  { id: 1, text: "And it helps 'cause I felt", range: [0, 3] },
  { id: 1, text: "I was down, I was out", range: [0, 3] },
  { id: 1, text: "Then you looked at me now", range: [0, 3] },
  { id: 1, text: "And said I see your monsters", range: [0, 3] },
  { id: 1, text: "I see your pain", range: [0, 3] },
  { id: 1, text: "Tell me your problems", range: [0, 3] },
  { id: 1, text: "I'll chase them away", range: [0, 3] },
  { id: 1, text: "I'll be your lighthouse", range: [0, 3] },
  { id: 1, text: "I'll make it okay", range: [0, 3] },
  { id: 1, text: "When I see your monsters", range: [0, 3] },
  { id: 1, text: "I'll stand there so brave", range: [0, 3] },
  { id: 1, text: "I see your monsters", range: [0, 3] },
  { id: 1, text: "I see your pain", range: [0, 3] },
  { id: 1, text: "Tell me your problems", range: [0, 3] },
  { id: 1, text: "I'll chase them away (chase them all away)", range: [0, 3] },
  { id: 1, text: "I'll be your lighthouse", range: [0, 3] },
  { id: 1, text: "I'll make it okay (make it okay)", range: [0, 3] },
  { id: 1, text: "When I see your monsters", range: [0, 3] },
  { id: 1, text: "(When I see your monsters)", range: [0, 3] },
  { id: 1, text: "I'll stand there so brave", range: [0, 3] },
  { id: 1, text: "And chase them all away", range: [0, 3] },
];

export const trouble_is_friend = [
  {
    id: 1,
    text: "Trouble will find you no mater where you go, oh oh",
    range: [0, 3],
  },
  {
    id: 1,
    text: "No Matter if you're fast no matter if you're slow, oh oh",
    range: [0, 3],
  },
  {
    id: 1,
    text: "The eye of the storm and the cry in the morn, oh oh",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Your fine for a while but then start to loose control",
    range: [0, 3],
  },
  { id: 1, text: "He's there in the dark", range: [0, 3] },
  { id: 1, text: "He's there in my heart", range: [0, 3] },
  { id: 1, text: "He waits in the winds", range: [0, 3] },
  { id: 1, text: "He's gotta play a part", range: [0, 3] },
  { id: 1, text: "Trouble is a friend", range: [0, 3] },
  { id: 1, text: "Yeah trouble is a friend of mine. oh oh", range: [0, 3] },
  {
    id: 1,
    text: "Trouble is a friend but trouble is a foe, oh oh",
    range: [0, 3],
  },
  {
    id: 1,
    text: "And no matter what I feed him he always seems to grow, oh oh",
    range: [0, 3],
  },
  {
    id: 1,
    text: "He sees what I see and he knows what I know, oh oh",
    range: [0, 3],
  },
  {
    id: 1,
    text: "So don't forget as you ease on down the road",
    range: [0, 3],
  },
  {
    id: 1,
    text: "So don't be alarmed if he takes you by the arm",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I won't let him win, but I'm a sucker for his charm",
    range: [0, 3],
  },
  { id: 1, text: "Trouble is a friend", range: [0, 3] },
  { id: 1, text: "Yeah trouble is a friend of mine, oh oh", range: [0, 3] },
  { id: 1, text: "Oh how I hate the way he makes me feel", range: [0, 3] },
  { id: 1, text: "And how I try to make him leave, I try", range: [0, 3] },
  { id: 1, text: "Oh Oh I try", range: [0, 3] },
];

export const cheri_cheri_lady = [
  { id: 1, text: "Oh, I cannot explain", range: [0, 3] },
  { id: 1, text: "Every time it's the same", range: [0, 3] },
  { id: 1, text: "Oh, I feel that it's real", range: [0, 3] },
  { id: 1, text: "Take my heart", range: [0, 3] },
  { id: 1, text: "I've been lonely too long", range: [0, 3] },
  { id: 1, text: "Oh, I can't be so strong", range: [0, 3] },
  { id: 1, text: "Take a chance for romance", range: [0, 3] },
  { id: 1, text: "Take my heart", range: [0, 3] },
  { id: 1, text: "I need you so", range: [0, 3] },
  { id: 1, text: "There's no time", range: [0, 3] },
  { id: 1, text: "I'll ever go", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Goin' through emotion", range: [0, 3] },
  { id: 1, text: "Love is where you find it", range: [0, 3] },
  { id: 1, text: "Listen to your heart", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Livin' in devotion", range: [0, 3] },
  { id: 1, text: "It's always like the first time", range: [0, 3] },
  { id: 1, text: "Let me take a part", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Like there's no tomorrow", range: [0, 3] },
  { id: 1, text: "Take my heart, don't lose it", range: [0, 3] },
  { id: 1, text: "Listen to your heart", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "To know you is to love you", range: [0, 3] },
  { id: 1, text: "If you call me baby", range: [0, 3] },
  { id: 1, text: "I'll be always yours", range: [0, 3] },
  { id: 1, text: "I get up and get down", range: [0, 3] },
  { id: 1, text: "Oh, my world turns around", range: [0, 3] },
  { id: 1, text: "Who is right? Who is wrong?", range: [0, 3] },
  { id: 1, text: "I don't know", range: [0, 3] },
  { id: 1, text: "I've got pain in my heart", range: [0, 3] },
  { id: 1, text: "Got a love in my soul", range: [0, 3] },
  { id: 1, text: "Easy come but I think easy go", range: [0, 3] },
  { id: 1, text: "I need you so", range: [0, 3] },
  { id: 1, text: "All those times", range: [0, 3] },
  { id: 1, text: "I'm not so strong", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Goin' through emotion", range: [0, 3] },
  { id: 1, text: "Love is where you find it", range: [0, 3] },
  { id: 1, text: "Listen to your heart", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Livin' in devotion", range: [0, 3] },
  { id: 1, text: "It's always like the first time", range: [0, 3] },
  { id: 1, text: "Let me take a part", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Like there's no tomorrow", range: [0, 3] },
  { id: 1, text: "Take my heart, don't lose it", range: [0, 3] },
  { id: 1, text: "Listen to your heart", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "To know you is to love you", range: [0, 3] },
  { id: 1, text: "If you call me baby", range: [0, 3] },
  { id: 1, text: "I'll be always yours", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Like there's no tomorrow", range: [0, 3] },
  { id: 1, text: "Take my heart, don't lose it", range: [0, 3] },
  { id: 1, text: "Listen to your heart", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "To know you is to love you", range: [0, 3] },
  { id: 1, text: "If you call me baby", range: [0, 3] },
  { id: 1, text: "I'll be yours", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "Like there's no tomorrow", range: [0, 3] },
  { id: 1, text: "Take my heart, don't lose it", range: [0, 3] },
  { id: 1, text: "Listen to your heart", range: [0, 3] },
  { id: 1, text: "Cheri Cheri Lady", range: [0, 3] },
  { id: 1, text: "To know you is to love you", range: [0, 3] },
  { id: 1, text: "If you call me baby", range: [0, 3] },
  { id: 1, text: "I'll be yours", range: [0, 3] },
];

export const sold_out = [
  { id: 1, text: "I ain't like no one you met before", range: [0, 3] },
  { id: 1, text: "I'm running for the front", range: [0, 3] },
  { id: 1, text: "When they're all running for the door", range: [0, 3] },
  { id: 1, text: "And I won't sit down won't back out", range: [0, 3] },
  { id: 1, text: "You can't ever shut me up", range: [0, 3] },
  { id: 1, text: "'Cause I'm on a mission", range: [0, 3] },
  { id: 1, text: "And I won't quit now", range: [0, 3] },
  { id: 1, text: "In a world full of followers", range: [0, 3] },
  { id: 1, text: "I'll be a leader", range: [0, 3] },
  { id: 1, text: "In a world full of doubters", range: [0, 3] },
  { id: 1, text: "I'll be a believer", range: [0, 3] },
  { id: 1, text: "I'm stepping out without a hesitation", range: [0, 3] },
  { id: 1, text: "Because the battle's already been won", range: [0, 3] },
  { id: 1, text: "I'm sold out", range: [0, 3] },
  { id: 1, text: "I'm no longer living", range: [0, 3] },
  { id: 1, text: "Just for myself", range: [0, 3] },
  { id: 1, text: "Running after Jesus", range: [0, 3] },
  { id: 1, text: "With my whole heart", range: [0, 3] },
  { id: 1, text: "And now I'm ready to shout", range: [0, 3] },
  { id: 1, text: "I am sold out", range: [0, 3] },
  { id: 1, text: "I'm sold out", range: [0, 3] },
  { id: 1, text: "With every single", range: [0, 3] },
  { id: 1, text: "Step that I take now", range: [0, 3] },
  { id: 1, text: "With every drop of blood", range: [0, 3] },
  { id: 1, text: "Left in my veins", range: [0, 3] },
  { id: 1, text: "I'm gonna be making it count", range: [0, 3] },
  { id: 1, text: "I am sold out", range: [0, 3] },
  { id: 1, text: "This ain't just some temporary phase", range: [0, 3] },
  { id: 1, text: "You can't face this kind of grace", range: [0, 3] },
  { id: 1, text: "And leave the way you came", range: [0, 3] },
  { id: 1, text: "This is permanent with intent", range: [0, 3] },
  { id: 1, text: "And there won't be no stopping it now", range: [0, 3] },
  { id: 1, text: "I'm on a mission and it's heaven sent", range: [0, 3] },
  { id: 1, text: "In a world full of followers", range: [0, 3] },
  { id: 1, text: "I'll be a leader", range: [0, 3] },
  { id: 1, text: "In a world full of doubters", range: [0, 3] },
  { id: 1, text: "I'll be a believer", range: [0, 3] },
  { id: 1, text: "I'm stepping out without a hesitation", range: [0, 3] },
  { id: 1, text: "'Cause my soul is like a stadium", range: [0, 3] },
  { id: 1, text: "And I'm sold out", range: [0, 3] },
  { id: 1, text: "I'm no longer living", range: [0, 3] },
  { id: 1, text: "Just for myself", range: [0, 3] },
  { id: 1, text: "Running after Jesus", range: [0, 3] },
  { id: 1, text: "With my whole heart", range: [0, 3] },
  { id: 1, text: "And now I'm ready to shout", range: [0, 3] },
  { id: 1, text: "I am sold out", range: [0, 3] },
  { id: 1, text: "I'm sold out", range: [0, 3] },
  { id: 1, text: "With every single", range: [0, 3] },
  { id: 1, text: "Step that I take now", range: [0, 3] },
  { id: 1, text: "With every drop of blood", range: [0, 3] },
  { id: 1, text: "Left in my veins", range: [0, 3] },
  { id: 1, text: "I'm gonna be making it count", range: [0, 3] },
  { id: 1, text: "I am sold out", range: [0, 3] },
  { id: 1, text: "No trials coming against me", range: [0, 3] },
  { id: 1, text: "Could put a dent in my passion", range: [0, 3] },
  { id: 1, text: "They're just an opportunity", range: [0, 3] },
  { id: 1, text: "To put my faith into action", range: [0, 3] },
  { id: 1, text: "In a world full of followers", range: [0, 3] },
  { id: 1, text: "I'll be a leader", range: [0, 3] },
  { id: 1, text: "In a world full of doubters", range: [0, 3] },
  { id: 1, text: "I'll be a believer", range: [0, 3] },
  { id: 1, text: "I'm stepping out without a hesitation", range: [0, 3] },
  { id: 1, text: "I ain't got nothing left to be afraid of", range: [0, 3] },
  { id: 1, text: "I'm sold out", range: [0, 3] },
  { id: 1, text: "I'm no longer living", range: [0, 3] },
  { id: 1, text: "Just for myself", range: [0, 3] },
  { id: 1, text: "Running after Jesus", range: [0, 3] },
  { id: 1, text: "With my whole heart", range: [0, 3] },
  { id: 1, text: "And now I'm ready to shout", range: [0, 3] },
  { id: 1, text: "I am sold out", range: [0, 3] },
  { id: 1, text: "I'm sold out", range: [0, 3] },
  { id: 1, text: "With every single", range: [0, 3] },
  { id: 1, text: "Step that I take now", range: [0, 3] },
  { id: 1, text: "With every drop of blood", range: [0, 3] },
  { id: 1, text: "Left in my veins", range: [0, 3] },
  { id: 1, text: "I'm gonna be making it count", range: [0, 3] },
  { id: 1, text: "I am sold out", range: [0, 3] },
];

export const until_you = [
  { id: 1, text: "Baby, life was good to me", range: [0, 3] },
  { id: 1, text: "But you just made it better", range: [0, 3] },
  { id: 1, text: "I love the way you stand by me", range: [0, 3] },
  { id: 1, text: "Through any kind of weather", range: [0, 3] },
  {
    id: 1,
    text: "I don't wanna run away, just wanna make your day",
    range: [0, 3],
  },
  {
    id: 1,
    text: "When you feel the world is on your shoulders",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I don't wanna make it worse, just wanna make us work",
    range: [0, 3],
  },
  { id: 1, text: "Baby, tell me I will do whatever", range: [0, 3] },
  {
    id: 1,
    text: "It feels like nobody ever knew me until you knew me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever loved me until you loved me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever touched me until you touched me",
    range: [0, 3],
  },
  { id: 1, text: "Baby, nobody, nobody until you", range: [0, 3] },
  { id: 1, text: "Baby, it just took one hit of you", range: [0, 3] },
  { id: 1, text: "Now I'm addicted", range: [0, 3] },
  { id: 1, text: "You never know what's missing", range: [0, 3] },
  { id: 1, text: "Till you get everything you needed", range: [0, 3] },
  {
    id: 1,
    text: "I don't wanna run away just wanna make your day",
    range: [0, 3],
  },
  {
    id: 1,
    text: "When you feel the world is on your shoulders",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I don't wanna make it worse just wanna make us work",
    range: [0, 3],
  },
  { id: 1, text: "Baby, tell me, I will do whatever", range: [0, 3] },
  {
    id: 1,
    text: "It feels like nobody ever knew me until you knew me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever loved me until you loved me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever touched me until you touched me",
    range: [0, 3],
  },
  { id: 1, text: "Baby, nobody, nobody until you", range: [0, 3] },
  {
    id: 1,
    text: "See it was enough to know, if I ever let you go",
    range: [0, 3],
  },
  { id: 1, text: "I would be no one", range: [0, 3] },
  {
    id: 1,
    text: "'Cause I never thought I'd feel all the things you made me feel",
    range: [0, 3],
  },
  { id: 1, text: "Wasn't looking for someone, oh, until you", range: [0, 3] },
  {
    id: 1,
    text: "It feels like nobody ever knew me until you knew me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever loved me until you loved me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever touched me until you touched me",
    range: [0, 3],
  },
  { id: 1, text: "Baby, nobody, nobody", range: [0, 3] },
  {
    id: 1,
    text: "It feels like nobody ever knew me until you knew me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever loved me until you loved me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Feels like nobody ever touched me until you touched me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Baby, nobody, nobody, nobody, nobody, until you",
    range: [0, 3],
  },
];

export const lemon_tree = [
  { id: 1, text: "I'm sitting here in a boring room", range: [0, 3] },
  { id: 1, text: "It's just another rainy Sunday afternoon", range: [0, 3] },
  { id: 1, text: "I'm wasting my time I got nothing to do", range: [0, 3] },
  { id: 1, text: "I'm hanging around I'm waiting for you", range: [0, 3] },
  { id: 1, text: "But nothing ever happens", range: [0, 3] },
  { id: 1, text: "And I wonder", range: [0, 3] },
  { id: 1, text: "I'm driving around in my car", range: [0, 3] },
  { id: 1, text: "I'm driving too fast, I'm driving too far", range: [0, 3] },
  { id: 1, text: "I'd like to change my point of view", range: [0, 3] },
  { id: 1, text: "I feel so lonely, I'm waiting for you", range: [0, 3] },
  { id: 1, text: "But nothing ever happens", range: [0, 3] },
  { id: 1, text: "And I wonder", range: [0, 3] },
  { id: 1, text: "I wonder how, I wonder why", range: [0, 3] },
  { id: 1, text: "Yesterday you told me 'bout the", range: [0, 3] },
  { id: 1, text: "Blue, blue sky", range: [0, 3] },
  { id: 1, text: "And all that I can see", range: [0, 3] },
  { id: 1, text: "Is just a yellow lemon tree", range: [0, 3] },
  { id: 1, text: "I'm turning my head up and down", range: [0, 3] },
  { id: 1, text: "I'm turning, turning, turning, turning", range: [0, 3] },
  { id: 1, text: "Turning around", range: [0, 3] },
  { id: 1, text: "And all that I can see", range: [0, 3] },
  { id: 1, text: "Is just another lemon tree", range: [0, 3] },
  { id: 1, text: "Sing dah", range: [0, 3] },
  { id: 1, text: "Dah-dah-dah-dam, dee-dab-dah", range: [0, 3] },
  { id: 1, text: "Dah-dah-dah-dam, dee-dab-dah", range: [0, 3] },
  { id: 1, text: "Dab-deedly dah", range: [0, 3] },
  { id: 1, text: "I'm sitting here, I miss the power", range: [0, 3] },
  { id: 1, text: "I'd like to go out, taking a shower", range: [0, 3] },
  { id: 1, text: "But there's a heavy cloud inside my head", range: [0, 3] },
  { id: 1, text: "I feel so tired, put myself into bed", range: [0, 3] },
  { id: 1, text: "Well, nothing ever happens", range: [0, 3] },
  { id: 1, text: "And I wonder", range: [0, 3] },
  { id: 1, text: "Isolation is not good for me", range: [0, 3] },
  { id: 1, text: "Isolation, I don't want to", range: [0, 3] },
  { id: 1, text: "Sit on a lemon tree", range: [0, 3] },
  { id: 1, text: "I'm steppin' around in a desert of joy", range: [0, 3] },
  { id: 1, text: "Maybe anyhow I'll get another toy", range: [0, 3] },
  { id: 1, text: "And everything will happen", range: [0, 3] },
  { id: 1, text: "And you wonder", range: [0, 3] },
  { id: 1, text: "I wonder how, I wonder why", range: [0, 3] },
  { id: 1, text: "Yesterday you told me 'bout the", range: [0, 3] },
  { id: 1, text: "Blue, blue sky", range: [0, 3] },
  { id: 1, text: "And all that I can see", range: [0, 3] },
  { id: 1, text: "Is just another yellow lemon tree", range: [0, 3] },
  { id: 1, text: "I'm turning my head up and down", range: [0, 3] },
  { id: 1, text: "I'm turning, turning, turning, turning", range: [0, 3] },
  { id: 1, text: "Turning around", range: [0, 3] },
  { id: 1, text: "And all that I can see", range: [0, 3] },
  { id: 1, text: "Is just a yellow lemon tree", range: [0, 3] },
  { id: 1, text: "And I wonder, wonder", range: [0, 3] },
  { id: 1, text: "I wonder how, I wonder why", range: [0, 3] },
  { id: 1, text: "Yesterday you told me 'bout the", range: [0, 3] },
  { id: 1, text: "Blue, blue sky", range: [0, 3] },
  { id: 1, text: "And all that I can see", range: [0, 3] },
  { id: 1, text: "And all that I can see", range: [0, 3] },
  { id: 1, text: "And all that I can see", range: [0, 3] },
  { id: 1, text: "Is just a yellow lemon tree", range: [0, 3] },
];

export const darkness = [
  { id: 1, text: "I don't wanna be alone", range: [0, 3] },
  { id: 1, text: "I don't wanna be", range: [0, 3] },
  { id: 1, text: "I don't wanna be alone", range: [0, 3] },
  { id: 1, text: "In the darkness", range: [0, 3] },
  { id: 1, text: "I don't wanna be alone", range: [0, 3] },
  { id: 1, text: "In the darkness", range: [0, 3] },
  { id: 1, text: "I don't wanna be alone", range: [0, 3] },
  { id: 1, text: "In the darkness anymore", range: [0, 3] },
  { id: 1, text: "Here I am, alone again", range: [0, 3] },
  { id: 1, text: "Can't get out of this hole I'm in", range: [0, 3] },
  { id: 1, text: "It's like the walls are closin' in", range: [0, 3] },
  { id: 1, text: "You can't help me, no one can", range: [0, 3] },
  { id: 1, text: "I can feel these curtains closin'", range: [0, 3] },
  { id: 1, text: "I go to open 'em", range: [0, 3] },
  { id: 1, text: "But something pulls 'em closed again", range: [0, 3] },
  { id: 1, text: "(Hello darkness, my old friend)", range: [0, 3] },
  { id: 1, text: "Feels like I'm loathing in Las Vegas", range: [0, 3] },
  { id: 1, text: "Haven't got the vaguest, why I'm so lost?", range: [0, 3] },
  { id: 1, text: "But I'd make you this small wager", range: [0, 3] },
  { id: 1, text: "If I bet you, I'll be in tomorrow's paper", range: [0, 3] },
  { id: 1, text: "Who would the odds favor?", range: [0, 3] },
  { id: 1, text: "(Hello darkness, my old friend)", range: [0, 3] },
  { id: 1, text: "I'm so much like my father", range: [0, 3] },
  { id: 1, text: "You would think that I knew him", range: [0, 3] },
  { id: 1, text: "I keep pacin' this room, Valium", range: [0, 3] },
  { id: 1, text: "Then chase it with booze", range: [0, 3] },
  { id: 1, text: "One little taste it'll do", range: [0, 3] },
  { id: 1, text: "Maybe I'll take and snooze", range: [0, 3] },
  { id: 1, text: "Then tear up the stage in a few", range: [0, 3] },
  { id: 1, text: "(Hello darkness, my old friend)", range: [0, 3] },
  {
    id: 1,
    text: "Fuck the Colt 45, I'ma need somethin' stronger",
    range: [0, 3],
  },
  {
    id: 1,
    text: "If I pop any caps, it better be off of vodka",
    range: [0, 3],
  },
  { id: 1, text: "Round after round after round", range: [0, 3] },
  { id: 1, text: "I'm gettin' loaded (Haha)", range: [0, 3] },
  { id: 1, text: "That's a lot of shots, huh?", range: [0, 3] },
  {
    id: 1,
    text: "Double entendre (Hello darkness, my old friend)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I don't wanna be alone in the darkness (Yeah)",
    range: [0, 3],
  },
  { id: 1, text: "I don't wanna be alone in the darkness", range: [0, 3] },
  {
    id: 1,
    text: "I don't wanna be alone in the darkness anymore",
    range: [0, 3],
  },
  { id: 1, text: "(Hello darkness my old friend)", range: [0, 3] },
  { id: 1, text: "Now I'm starin' at the room", range: [0, 3] },
  { id: 1, text: "Service menu off a Benzo", range: [0, 3] },
  { id: 1, text: "I can hear the music", range: [0, 3] },
  { id: 1, text: "Continue to crescendo", range: [0, 3] },
  { id: 1, text: "I can see the whole venue from my window", range: [0, 3] },
  {
    id: 1,
    text: "That's when you know you're schizo (Hello darkness my old friend)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "'Cause I keep peakin' out the curtain from the hotel",
    range: [0, 3],
  },
  { id: 1, text: "The music is so loud", range: [0, 3] },
  { id: 1, text: "But it's almost as though", range: [0, 3] },
  { id: 1, text: "I don't hear no sound", range: [0, 3] },
  { id: 1, text: "I should get ready for the show now", range: [0, 3] },
  { id: 1, text: "Wait, is this the whole crowd?", range: [0, 3] },
  { id: 1, text: "I thought this was sold out", range: [0, 3] },
  { id: 1, text: "(Hello darkness my old friend)", range: [0, 3] },
  { id: 1, text: "But it's only the opening act", range: [0, 3] },
  { id: 1, text: "It's early don't overreact", range: [0, 3] },
  { id: 1, text: "Then something told me, relax", range: [0, 3] },
  { id: 1, text: "And just hope for the show to be packed", range: [0, 3] },
  { id: 1, text: "Don't wanna hit the stage", range: [0, 3] },
  { id: 1, text: "Before they fill each row to the max", range: [0, 3] },
  { id: 1, text: "'Cause that'd be totally wack", range: [0, 3] },
  {
    id: 1,
    text: "You can't murder a show nobody's at (Hello darkness my old friend)",
    range: [0, 3],
  },
  { id: 1, text: "But what if nobody shows?", range: [0, 3] },
  { id: 1, text: "Panic mode, 'bout to snap and go", range: [0, 3] },
  { id: 1, text: "Mother- wacko at any second", range: [0, 3] },
  { id: 1, text: "'Bout to cancel the show", range: [0, 3] },
  { id: 1, text: "Just as fans below rush the entrance", range: [0, 3] },
  { id: 1, text: "Plan is a go to wreck-", range: [0, 3] },
  {
    id: 1,
    text: "Cameras in all directions (Hello darkness my old friend)",
    range: [0, 3],
  },
  { id: 1, text: "The press is about to go ape-", range: [0, 3] },
  { id: 1, text: "Bananas on all the networks", range: [0, 3] },
  { id: 1, text: "Commando with extra clips", range: [0, 3] },
  { id: 1, text: "I got ammo for all the hecklers", range: [0, 3] },
  { id: 1, text: "I'm armed to the teeth", range: [0, 3] },
  { id: 1, text: "Another - fall off the bed", range: [0, 3] },
  { id: 1, text: "Hit the ground and crawl to the dresser", range: [0, 3] },
  {
    id: 1,
    text: "Alcohol on my breath as I reach for the scope",
    range: [0, 3],
  },
  { id: 1, text: "I'm blackin' out I'm all out of meds", range: [0, 3] },
  { id: 1, text: "With them Benzodiazepines gone", range: [0, 3] },
  {
    id: 1,
    text: "Now it's just magazines sprawled out on the floor",
    range: [0, 3],
  },
  { id: 1, text: "Off the media", range: [0, 3] },
  { id: 1, text: "I'm goin' all out, this is war", range: [0, 3] },
  { id: 1, text: "(Hello darkness my old friend)", range: [0, 3] },
  {
    id: 1,
    text: "And I don't wanna be alone in the darkness (Yeah)",
    range: [0, 3],
  },
  { id: 1, text: "I don't wanna be alone in the darkness", range: [0, 3] },
  {
    id: 1,
    text: "I don't wanna be alone in the darkness anymore",
    range: [0, 3],
  },
  { id: 1, text: "People start to show up", range: [0, 3] },
  { id: 1, text: "Time to start the show up", range: [0, 3] },
  { id: 1, text: "It's 10:05 p.m. and", range: [0, 3] },
  { id: 1, text: "The curtain starts to go up", range: [0, 3] },
  { id: 1, text: "And I'm already sweatin'", range: [0, 3] },
  { id: 1, text: "But I'm locked and loaded", range: [0, 3] },
  { id: 1, text: "For rapid fire spittin'", range: [0, 3] },
  { id: 1, text: "For all the concert goers", range: [0, 3] },
  { id: 1, text: "Scopes for sniper vision", range: [0, 3] },
  { id: 1, text: "Surprise from out of nowhere", range: [0, 3] },
  { id: 1, text: "As I slide the clip in", range: [0, 3] },
  { id: 1, text: "From inside the hotel", range: [0, 3] },
  { id: 1, text: "Leanin' out the window", range: [0, 3] },
  { id: 1, text: "Going Keyser Söze", range: [0, 3] },
  { id: 1, text: "Finger on the trigger", range: [0, 3] },
  { id: 1, text: "But I'm a licensed owner", range: [0, 3] },
  { id: 1, text: "With no prior convictions", range: [0, 3] },
  { id: 1, text: "So lost, the sky's the limit", range: [0, 3] },
  { id: 1, text: "So my supplies infinite", range: [0, 3] },
  { id: 1, text: "Strapped like I'm a solider", range: [0, 3] },
  { id: 1, text: "Got 'em hopping over", range: [0, 3] },
  { id: 1, text: "Walls and climbing fences", range: [0, 3] },
  { id: 1, text: "Some of them John Travolta", range: [0, 3] },
  {
    id: 1,
    text: "Staying alive by inches (Hello darkness my old friend)",
    range: [0, 3],
  },
  { id: 1, text: "Cops are knockin', oh-", range: [0, 3] },
  { id: 1, text: "Thought I blocked the entrance", range: [0, 3] },
  { id: 1, text: "Guess show time is over", range: [0, 3] },
  { id: 1, text: "No suicide note", range: [0, 3] },
  { id: 1, text: "Just a note for target distance", range: [0, 3] },
  { id: 1, text: "But if you'd like to know", range: [0, 3] },
  { id: 1, text: "The reason why I did this", range: [0, 3] },
  { id: 1, text: "You'll never find a motive", range: [0, 3] },
  { id: 1, text: "Truth is I have no idea", range: [0, 3] },
  { id: 1, text: "I am just as stumped", range: [0, 3] },
  { id: 1, text: "No signs of mental illness", range: [0, 3] },
  { id: 1, text: "Just tryin' to show ya", range: [0, 3] },
  { id: 1, text: "The reason why we're so fucked", range: [0, 3] },
  { id: 1, text: "'Cause by the time it's over", range: [0, 3] },
  { id: 1, text: "Won't make the slightest difference", range: [0, 3] },
  { id: 1, text: "(Hello darkness my old friend)", range: [0, 3] },
  { id: 1, text: "I don't wanna be alone in the darkness", range: [0, 3] },
  { id: 1, text: "I don't wanna be alone in the darkness", range: [0, 3] },
  {
    id: 1,
    text: "I don't wanna be alone in the darkness anymore",
    range: [0, 3],
  },
  { id: 1, text: "(Hello darkness my old friend)", range: [0, 3] },
  { id: 1, text: "Yeah, we do have some breaking news", range: [0, 3] },
  { id: 1, text: "From the Associated Press right now", range: [0, 3] },
  { id: 1, text: "Just gonna bring that up because", range: [0, 3] },
  { id: 1, text: "We are hearing we have told you", range: [0, 3] },
  { id: 1, text: "That the shooter is dead", range: [0, 3] },
  { id: 1, text: "And we have just learned that", range: [0, 3] },
  {
    id: 1,
    text: "Police are saying that the Las Vegas shooter killed himself",
    range: [0, 3],
  },
  { id: 1, text: "That is the bartender there at Mandalay bay", range: [0, 3] },
  { id: 1, text: "And I believe we're going to learn more", range: [0, 3] },
  { id: 1, text: "Yeah, we just wanted to share that with you", range: [0, 3] },
  { id: 1, text: "You can see behind me here", range: [0, 3] },
  { id: 1, text: "This is what he looks like", range: [0, 3] },
  { id: 1, text: "Now we did just tell you that", range: [0, 3] },
  { id: 1, text: "Police just earlier", range: [0, 3] },
  { id: 1, text: "Metro was telling us", range: [0, 3] },
  { id: 1, text: "That he killed himself", range: [0, 3] },
  { id: 1, text: "Inside the hotel room", range: [0, 3] },
  { id: 1, text: "Good morning as we come to you", range: [0, 3] },
  { id: 1, text: "On the air we bring you breaking news", range: [0, 3] },
  { id: 1, text: "A school shooting", range: [0, 3] },
  { id: 1, text: "Another school shooting", range: [0, 3] },
  { id: 1, text: "Reports of a number of fatalities", range: [0, 3] },
  { id: 1, text: "And this time it is in Santa Fe, Texas", range: [0, 3] },
  { id: 1, text: "That is just outside Galvaston", range: [0, 3] },
  { id: 1, text: "Last night's mass shooting", range: [0, 3] },
  { id: 1, text: "At Southern California", range: [0, 3] },
  { id: 1, text: "We are following breaking news", range: [0, 3] },
  { id: 1, text: "This morning another deadly school shooting", range: [0, 3] },
  { id: 1, text: "This one in Santa Fe, Texas", range: [0, 3] },
  { id: 1, text: "It's just outside Houston", range: [0, 3] },
  { id: 1, text: "26 killed and 20 others wounded", range: [0, 3] },
  { id: 1, text: "(Hello darkness my old friend)", range: [0, 3] },
  { id: 1, text: "This, a deadly shooting at a food festival", range: [0, 3] },
  { id: 1, text: "In Northern California", range: [0, 3] },
  { id: 1, text: "Three people so far dead", range: [0, 3] },
  {
    id: 1,
    text: "Breaking news a deadly shooting in a Newspaper office in Annapolis",
    range: [0, 3],
  },
  { id: 1, text: "Newly released surveillance video", range: [0, 3] },
  {
    id: 1,
    text: "Shows the moments leading up to the mass shooting",
    range: [0, 3],
  },
  { id: 1, text: "In Dayton, Ohio", range: [0, 3] },
];

export const paind_my_dues = [
  {
    id: 1,
    text: "Clicks, clicks, clicks, they'll do anything to get a few",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Tick, tick, tick, that's the sound before my head explodes",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Quit, quit, quit, look at you up on your pedestals",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Quick, quick, quick, here the critics come it's time to go",
    range: [0, 3],
  },
  { id: 1, text: "I read your article it kinda hurt me", range: [0, 3] },
  {
    id: 1,
    text: "I don't know who hired you or what your friends say in your circle",
    range: [0, 3],
  },
  {
    id: 1,
    text: "But the fact that you released it, tells me two things are for certain",
    range: [0, 3],
  },
  {
    id: 1,
    text: "They get paid for trashin' people, I get paid cause I stay workin'",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Drop the search and they emerge up out of nowhere to the surface",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Just to peek behind the curtain, throwin' salt at all my burdens",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I'm aware I shouldn't give this my attention, life's a journey",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I should just stay on my path and learn to laugh",
    range: [0, 3],
  },
  { id: 1, text: "You think they heard me?", range: [0, 3] },
  {
    id: 1,
    text: "Ears are burning put 'em out, quiet quiet look around",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Why don't they find someone way more interesting to write about?",
    range: [0, 3],
  },
  { id: 1, text: "Us we're kinda boring, aren't we?", range: [0, 3] },
  { id: 1, text: "All we do is whine and pout", range: [0, 3] },
  {
    id: 1,
    text: "It's confusing so amusing how I argue with myself (hello)",
    range: [0, 3],
  },
  { id: 1, text: "I spit it with ease, so leave it to me", range: [0, 3] },
  { id: 1, text: "You doubt it but you better believe", range: [0, 3] },
  {
    id: 1,
    text: "I'm on a rampage hit 'em with the record release",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Dependin' the week, I'm prolly gonna have to achieve another goal",
    range: [0, 3],
  },
  { id: 1, text: "Let me go when I'm over the beat", range: [0, 3] },
  {
    id: 1,
    text: "I go into beast mode like I'm ready to feast",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I'm fed up with these thieves tryna get me to bleed",
    range: [0, 3],
  },
  {
    id: 1,
    text: "They wanna see me take an L? (yup, see what I mean)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "How many records I gotta give you to get with the program?",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Taken for granted I'm 'bout to give you the whole plan",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Open your mind up and take a look at the blueprint",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Debate if you gotta, but gotta hold it with both hands",
    range: [0, 3],
  },
  { id: 1, text: "To pick up the bars you gotta be smart", range: [0, 3] },
  {
    id: 1,
    text: "You really gotta dig in your heart if you wanna get to the root of an issue",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Pursuin' the mental can be dark and be difficult",
    range: [0, 3],
  },
  {
    id: 1,
    text: "But the payoff at the end of it, can help you to get through it, hey",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Paid my dues, made it through (whoo, whoo, whoo)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Spread the news, I'm on the loose (whoo, whoo, whoo)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Makin' moves, I need some room (whoo, whoo, whoo)",
    range: [0, 3],
  },
  { id: 1, text: "Thought we's cool", range: [0, 3] },
  { id: 1, text: "Well don't assume, don't assume hey!", range: [0, 3] },
  { id: 1, text: "I'm the truth, oh they want some proof", range: [0, 3] },
  { id: 1, text: "Here don't be rude, somethin' new", range: [0, 3] },
  { id: 1, text: "Even when I lose I make it look cool", range: [0, 3] },
  { id: 1, text: "Do the show, then we hit the room", range: [0, 3] },
  { id: 1, text: "Wife is lookin' ooh, what to do?", range: [0, 3] },
  { id: 1, text: "I don't need the shades up to like the view", range: [0, 3] },
  {
    id: 1,
    text: "It's time to get back in the swing of things",
    range: [0, 3],
  },
  {
    id: 1,
    text: "When my life crashes, I'm not the guy that'll flee the scene",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I'll take ownership and own it and raise my hand if it's me",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Just remember though, I'm only a man, I'm a human being",
    range: [0, 3],
  },
  { id: 1, text: "Don't they see? Shoot the breeze", range: [0, 3] },
  { id: 1, text: "I'd rather just stay discrete", range: [0, 3] },
  {
    id: 1,
    text: "People claim they're in your corner but leave you in times of need",
    range: [0, 3],
  },
  { id: 1, text: "They don't listen, do they? (what?)", range: [0, 3] },
  { id: 1, text: "They don't listen to anything", range: [0, 3] },
  {
    id: 1,
    text: "I'll accept advice if it's not presented ignorantly",
    range: [0, 3],
  },
  { id: 1, text: "Look, costs are high they multiply", range: [0, 3] },
  { id: 1, text: "Then cause divides I'm forced to fight", range: [0, 3] },
  {
    id: 1,
    text: "The poison I been sippin' on has quite the bite",
    range: [0, 3],
  },
  { id: 1, text: "It killed me twice, they rigged the lights", range: [0, 3] },
  {
    id: 1,
    text: "So y'all can see the parts of mine that aren't so bright",
    range: [0, 3],
  },
  {
    id: 1,
    text: "See, often I apologize then authorize the awful times",
    range: [0, 3],
  },
  { id: 1, text: "To pop up (Nate) like I'm right behind you", range: [0, 3] },
  {
    id: 1,
    text: "I'd advise you not to try to climb inside the mind like I do",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Keep the rhyme book, expedite it, overnight it",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Hold it tight an' hope that time is on my side",
    range: [0, 3],
  },
  {
    id: 1,
    text: "'Cause if it's not then I'll decide to override my own demise",
    range: [0, 3],
  },
  {
    id: 1,
    text: "I toe the line too close and I could improvise, I'd empathize",
    range: [0, 3],
  },
  {
    id: 1,
    text: "But recognize the fact that I could jeopardize and wreck our lives",
    range: [0, 3],
  },
  {
    id: 1,
    text: "You better give me your attention the undivided",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Paid my dues, made it through (whoo, whoo, whoo)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Spread the news, I'm on the loose (whoo, whoo, whoo)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Makin' moves, I need some room (whoo, whoo, whoo)",
    range: [0, 3],
  },
  { id: 1, text: "Thought we's cool", range: [0, 3] },
  { id: 1, text: "Well don't assume, don't assume hey!", range: [0, 3] },
  {
    id: 1,
    text: "Paid my dues, made it through (whoo, whoo, whoo)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Spread the news, I'm on the loose (whoo, whoo, whoo)",
    range: [0, 3],
  },
  {
    id: 1,
    text: "Makin' moves, I need some room (whoo, whoo, whoo)",
    range: [0, 3],
  },
  { id: 1, text: "Thought we's cool", range: [0, 3] },
  { id: 1, text: "Well don't assume, don't assume hey!", range: [0, 3] },
];
